version: '3.6'
services:
  db-mysql:
    image: mysql:8.0.16
    container_name: mysql-gateway
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Password1!
      MYSQL_DATABASE: gateway
      MYSQL_USER: root
      MYSQL_PASSWORD: Password1!
    restart: always
    ports:
      - '3306:3306'

  mail:
    image: djfarrelly/maildev
    container_name: mail-gateway
    ports:
      - 1080:80
      - '25:25'
